### ISSUE TITLE
Not Compatible with React Native

### ISSUE THREAD

**Issue by judygab** [uuidjs/uuid#408]
## Describe the bug
I installed uuid in my react native project, following the instructions in readme and encountered problems with it.
I followed the steps of clearing caches, deleting node modules and installing.
I'm attaching the image of the error that I am getting.
<img width="394" alt="Screen Shot 2020-03-24 at 9 47 51 AM" src="https://user-images.githubusercontent.com/50160672/77432955-1f4efd80-6db5-11ea-94c7-2eaefec00410.png">

## Runtime

- OS: macOS
- Runtime: react-native
- Runtime Version: 0.61.5

**Comment by LinusU** [comment]
In version 7 of UUID we have deprecated the direct imports. Instead of importing from `uuid/v1`, could you try to import it as such:

```
import { v1 as uuidV1 } from 'uuid'
```

**Comment by ctavan** [comment]
As commented by @LinusU, deep requires are deprecated. It was indeed unintended, that we actually broke them for non-node environments, but we will probably not change that.

See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.

**Comment by judygab** [comment]
This breaks before the import though.

**Comment by LinusU** [comment]
It probably breaks when constructing the dependency tree, but if you change the import that should fix it. Did you try to change the import?

**Comment by ctavan** [comment]
Hmm, we could use https://github.com/TooTallNate/util-deprecate 🤔

**Comment by judygab** [comment]
Yeah, I tried that import but still getting the same error, does this require installing pods?

**Comment by ctavan** [comment]
@judygab did follow the polyfilling instructions from https://github.com/LinusU/react-native-get-random-values#readme ?

What does your exact import code look like?

**Comment by kopax** [comment]
Hello, I just discovered your module and I am using react-native.

My target are iOS, Android and web, this is my import:

```jsx
import { v4 as uuidv4 } from 'uuid';
```

It work fine with iOS and Android, but I have the following error on the web:

    Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.


I am using uuid v7.0.2, any idea how I can fix this?

**Comment by ctavan** [comment]
Can you clear all build caches/node_modules directories/etc. and try again? This looks like some legacy code survived the upgrade and not like a problem with the `uuid` library.

In particular, search your code base for `uuid/v4` and upgrade all legacy import statements as described in https://github.com/uuidjs/uuid#deep-requires-now-deprecated

**Comment by kopax** [comment]
@ctavan you are wrong, I never used your module before. I never heard of it before today when I was looking on how to get a filename for pictures taken with expo with the webcam.

**Comment by TrySound** [comment]
Some module may not list its uuid in dependencies and use the root one instead. This might trigger warning. Try to add console.trace in uuid/v4.js to see which module trigger this.

**Comment by kopax** [comment]
Ok, i'll do it now: `console.trace` and update this post

> Small - Zero-dependency, small footprint, plays nice with "tree shaking" packagers

**Comment by TrySound** [comment]
Looks like they fixed this in master. Need to ping them to publish new version.

**Comment by kopax** [comment]
I have checked the commit and the PR title is a bit confusing... How did they "make it work"? Did they just removed it?

**Comment by TrySound** [comment]
https://github.com/expo/expo/commit/d0bc483df71b999d539f16e94f276fba70e2c65a#diff-ce3eb7300b89a57b05be12979132e0bcR43-R46

**Comment by kopax** [comment]
Thanks for the link.

> Need to ping them to publish new version.

Expo is not publishing often so I'll just stay with v3.4.0 till they upgrade. I believe this will still do the job.

**Comment by judygab** [comment]
> In version 7 of UUID we have deprecated the direct imports. Instead of importing from `uuid/v1`, could you try to import it as such:
> 
> ```ts
> import { v1 as uuidv1 } from 'uuid'
> 
> uuidv1() // ⇨ '2c5ea4c0-4067-11e9-8b2d-1b9d6bcdbbfd'
> ```

I have tried that, didn't work.

**Comment by ctavan** [comment]
@judygab maybe you're having the same issue as https://github.com/uuidjs/uuid/issues/408#issuecomment-606070136 ?

**Comment by judygab** [comment]
@ctavan I don't think so, I'm not using Expo.

**Comment by TrySound** [comment]
Any package may forget to add uuid to dependencies. Try to add console.trace too.

**Comment by judygab** [comment]
Agreed, but this was not happening until I installed uuid specifically.

**Comment by ctavan** [comment]
@judygab I think that we're not finding a solution to your problem with further guesswork.

Could you please provide exact steps to reproduce (including all source code necessary to run into the error) so that we can find your issue (http://sscce.org/)? Thanks!

**Comment by juhana** [comment]
The same error happens on a clean React Native project with no other dependencies added except uuid. If it's caused by an old version being used in the project, it looks like React Native's xcode package uses version 3.4.0 (and Jest, but that should affect only tests.)

```
➜ yarn why uuid
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "uuid"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "uuid@8.0.0"
info Has been hoisted to "uuid"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "240KB"
info Disk size with unique dependencies: "240KB"
info Disk size with transitive dependencies: "240KB"
info Number of shared dependencies: 0
=> Found "xcode#uuid@3.4.0"
info This module exists because "react-native#@react-native-community#cli-platform-ios#xcode" depends on it.
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
=> Found "node-notifier#uuid@7.0.3"
info This module exists because "jest#@jest#core#@jest#reporters#node-notifier" depends on it.
info Disk size without dependencies: "252KB"
info Disk size with unique dependencies: "252KB"
info Disk size with transitive dependencies: "252KB"
info Number of shared dependencies: 0
=> Found "request#uuid@3.4.0"
info This module exists because "jest#@jest#core#jest-config#jest-environment-jsdom#jsdom#request" depends on it.
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "92KB"
info Disk size with transitive dependencies: "92KB"
info Number of shared dependencies: 0
✨  Done in 0.88s.
```

**Comment by ctavan** [comment]
@judygab are you still experiencing this issue?

**Comment by judygab** [comment]
> @judygab are you still experiencing this issue?

Yes, I could not find the solution and ended up not using the module.

**Comment by ctavan** [comment]
Sad to hear this @judygab.

@juhana were you able to solve your issue?

**Comment by juhana** [comment]
When I tried it last week, it didn't work because of other problems with React Native that are tracked in other issues. But as far as I can tell this specific issue is not a problem anymore.

**Comment by ctavan** [comment]
Thanks for the update @juhana !

Closing since it doesn't seem to affect active users anymore. Please feel free to open a new issue if anything comes up.
